"""time

Revision ID: 01a7b217e101
Revises: fecf2bdcbd3b
Create Date: 2018-09-11 12:02:37.615271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a7b217e101'
down_revision = 'fecf2bdcbd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'time')
    # ### end Alembic commands ###
