"""pass secure  Migration

Revision ID: 3939f58696c5
Revises: 
Create Date: 2018-09-09 12:21:05.003435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3939f58696c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_secure')
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
