"""fifth  Migration

Revision ID: 532495b61477
Revises: 3939f58696c5
Create Date: 2018-09-10 00:30:21.710620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532495b61477'
down_revision = '3939f58696c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'time')
    # ### end Alembic commands ###
